---
- name: Install fstab
  template: src=fstab.j2 dest=/etc/fstab

- name: mount /boot
  command: mount /boot 2> /dev/null || true
    creates=/boot/uEnv.txt

- name: Install uEnv.txt
  template: src=uEnv.txt.j2 dest=/boot/uEnv.txt

- name: Install sunxi-tools
  pacman: name=sunxi-tools state=present
