---
- name: Install common system packages
  pacman: name={{ item }} state=present
  with_items:
  - archey3
  - autoconf
  - automake
  - cronie
  - fortune
  - gcc
  - git
  - make
  - wget

- name: Install pacman -Sy to cron
  cron: name="Update pacman repositories" job="pacman -Sy" hour=0 state=present

- name: Install command-not-found hook
  pacman: name=pkgfile state=present
  notify:
  - update pkgfile db
  - install pkgfile cron

- name: Process and copy Bash sources
  template: src={{ item }}.j2 dest=/usr/local/etc/{{ item }}
  with_items:
  - bash.bashrc
  - bash_aliases.bash
  - bash_colours.bash

- name: Enable bash.bashrc
  lineinfile: dest=/etc/bash.bashrc line="[ -f /usr/local/etc/bash.bashrc ] && . /usr/local/etc/bash.bashrc" state=present
