---
- name: Sync pacman repositories
  pacman: update_cache=yes

- name: Install common system packages
  pacman: name={{ item }} state=present
  with_items:
  - archey3
  - autoconf
  - automake
  - cronie
  - gcc
  - git
  - make

- name: Install command-not-found hook
  pacman: name=pkgfile state=present
  notify:
  - update pkgfile db
  - install pkgfile cron
