---
- name: Generate locales
  lineinfile: dest=/etc/locale.gen line="{{ item }}" state=present
  with_items:
  - en_GB.UTF-8 UTF-8
  - en_US.UTF-8 UTF-8
  notify:
  - regenerate locales
  - set locale

- name: Set timezone to UTC
  file:
    src=/usr/share/zoneinfo/UTC
    dest=/etc/localtime
    state=link
    force=yes

- name: Install common system packages
  pacman: name={{ item }} state=present
  with_items:
  - autoconf
  - automake
  - cronie
  - dnsutils
  - fortune-mod
  - gcc
  - git
  - make
  - traceroute
  - wget

- name: Enable system services
  service: name={{ item }} enabled=yes state=started
  with_items:
  - cronie.service

- name: Configure multi-user boot target
  command: systemctl set-default -f multi-user.target
    creates=/etc/systemd/system/default.target

- name: Install pacman -Sy to cron
  cron: name="Update pacman repositories" job="pacman -Sy" minute=0 state=present

- name: Install ansible-pull to cron
  cron:
    name="Run server provisioning"
    job="cd /root/pi-server && ansible-pull -i inventory.ini -o -U {{ git_remote }}"
    minute=*/15
    state=present

- name: Install command-not-found hook
  pacman: name=pkgfile state=present
  notify:
  - update pkgfile db
  - install pkgfile cron

- name: Process and copy Bash sources
  template: src={{ item }}.j2 dest=/usr/local/etc/{{ item }}
  with_items:
  - bash.bashrc
  - bash_aliases.bash
  - bash_colours.bash

- name: Enable bash.bashrc
  lineinfile:
    dest=/etc/bash.bashrc
    line="[ -f /usr/local/etc/bash.bashrc ] && . /usr/local/etc/bash.bashrc"
    state=present

- name: Install authorised keys autoupdater
  template:
    src=update-authorised-keys.j2
    dest=/usr/local/bin/update-authorised-keys
    mode=755
    owner=root
    group=root

- name: Ensure /root/.ssh directory exists
  command: mkdir /root/.ssh
    creates=/root/.ssh


- name: Install RSA public key
  copy:
    src=rr.rossmann@me.com.pub
    dest=/root/.ssh/rr.rossmann@me.com.pub
    mode=600
    owner=root
    group=root
  notify:
  - update authorised keys

- name: Configure /etc/hosts
  template:
    src=hosts.j2
    dest=/etc/hosts
    mode=644
    owner=root
    group=root
