---
- name: update pkgfile db
  command: pkgfile -u

- name: install pkgfile cron
  cron: name="Update pkgfile database" job="pkgfile -u" hour=1 state=present

- name: regenerate locales
  command: locale-gen

- name: set locale
  template: src=locale.conf.j2 dest=/etc/locale.conf

- name: mount /boot
  mount: name=/boot src=/dev/mmcblk0p1 fstype=vfat state=mounted
